ignore:
- a
- an
- the
- and
- or
- but
- if
- because
- as
- what
- which
- who
- whom
- this
- that
- these
- those
- am
- is
- are
- was
- were
- be
- been
- being
- have
- has
- had
- do
- does
- did
- to
- at
- by
- for
- with
- about
- against
- between
- into
- through
- during
- before
- after
- above
- below
- from
- up
- down
- in
- out
- true
- false
- over
- under
- again
- further
- then
- once
- here
- there
- when
- where
- why
- how
- all
- any
- both
- each
- few
- more
- most
- other
- some
- such
- false
- nor
- not
- only
- own
- same
- so
- than
- too
- very
- can
- will
- just
- should
- now
- etc
- ie
- eg
- example
models:
- description: Word2Vec trained on general text corpus
  file: word2vec_default.json
  name: Word2Vec (Default)
- description: GloVe embeddings with 300 dimensions
  file: glove_embedding.json
  name: GloVe
- description: FastText model with subword information
  file: fasttext_embedding.json
  name: FastText
- description: Custom word embedding model
  file: embedding_data.json
  name: Custom Model
- description: 'Word embedding model: Word2Vec Sample'
  file: word2vec_sample.json
  name: Word2Vec Sample
- description: 'Word embedding model: Prn2Vec'
  file: prn2vec.json
  name: Prn2Vec
- description: 'Word embedding model: Fasttext Sample'
  file: fasttext_sample.json
  name: Fasttext Sample
- description: 'Word embedding model: Glove Twitter 25D'
  file: glove_twitter_25d.json
  name: Glove Twitter 25D
