ignore:
- a
- an
- the
- and
- or
- but
- if
- because
- as
- what
- which
- who
- whom
- this
- that
- these
- those
- am
- is
- are
- was
- were
- be
- been
- being
- have
- has
- had
- do
- does
- did
- to
- at
- by
- for
- with
- about
- against
- between
- into
- through
- during
- before
- after
- above
- below
- from
- up
- down
- in
- out
- true
- false
- over
- under
- again
- further
- then
- once
- here
- there
- when
- where
- why
- how
- all
- any
- both
- each
- few
- more
- most
- other
- some
- such
- false
- nor
- not
- only
- own
- same
- so
- than
- too
- very
- can
- will
- just
- should
- now
models:
- description: Tiny demo model (Tiny Word2Vec)
  file: tiny_word2vec.json
  name: Tiny Word2Vec
- description: Tiny demo model (Tiny Fasttext)
  file: tiny_fasttext.json
  name: Tiny Fasttext
- description: Tiny demo model (Tiny Custom)
  file: tiny_custom.json
  name: Tiny Custom
- description: Pre-trained Glove Twitter 25 from Gensim
  file: glove_twitter_25.json
  name: Glove Twitter 25
- description: Pre-trained Conceptnet Numberbatch 17 06 300 from Gensim
  file: conceptnet_numberbatch_17_06_300.json
  name: Conceptnet Numberbatch 17 06 300
- description: Pre-trained Fasttext Wiki News Subwords 300 from Gensim
  file: fasttext_wiki_news_subwords_300.json
  name: Fasttext Wiki News Subwords 300
